#!/usr/bin/env python3
"""Flatten plugins/ into single-file bundles that any assistant can load.

Claude Code and Claude Desktop read plugins/ directly and load one SKILL.md at a
time (progressive disclosure). ChatGPT, Grok, Gemini and most other assistants have
no such mechanism -- they take one blob of instructions. This script produces that
blob: one bundle per plugin, plus an all-in-one, plus a compact router-only file for
platforms with a tight instruction budget.

Usage (from the repo root):
    python tools/build_portable.py

Writes into portable/. Idempotent -- safe to re-run after editing any SKILL.md.
"""

from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLUGINS = ROOT / "plugins"
PORTABLE = ROOT / "portable"

# Order matters: this is the order skills appear in a bundle.
PLUGIN_ORDER = ["productivity", "product-management", "operations", "artifact-toolkit"]

PLUGIN_TITLES = {
    "productivity": "Productivity",
    "product-management": "Product Management",
    "operations": "Operations",
    "artifact-toolkit": "Artifact Toolkit",
}


# --------------------------------------------------------------------------- parsing

def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Return (frontmatter dict, body). Handles the flat key: value YAML skills use."""
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    raw = text[3:end].strip("\n")
    body = text[end + 4 :].lstrip("\n")

    meta: dict[str, str] = {}
    key = None
    for line in raw.splitlines():
        m = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if m:
            key = m.group(1)
            meta[key] = m.group(2).strip().strip('"')
        elif key and line.startswith((" ", "\t")):
            meta[key] += " " + line.strip()
    return meta, body


def demote_headings(body: str, levels: int = 1) -> str:
    """Push every ATX heading down N levels so skills nest under a bundle heading.

    Fenced code blocks are left alone -- several skills contain markdown templates
    whose '#' lines are output examples, not document structure.
    """
    out, in_fence, fence = [], False, ""
    for line in body.splitlines():
        stripped = line.lstrip()
        if stripped.startswith(("```", "~~~")):
            marker = stripped[:3]
            if not in_fence:
                in_fence, fence = True, marker
            elif marker == fence:
                in_fence, fence = False, ""
            out.append(line)
            continue
        if not in_fence and line.startswith("#"):
            hashes = len(line) - len(line.lstrip("#"))
            line = "#" * min(hashes + levels, 6) + line[hashes:]
        out.append(line)
    return "\n".join(out)


def rewrite_links(body: str, plugin: str) -> str:
    """Relative paths mean nothing in a pasted bundle. Point them at the section."""
    body = body.replace("[CONNECTORS.md](../../CONNECTORS.md)", "the **Connectors** section above")
    body = re.sub(r"\]\(\.\./\.\./CONNECTORS\.md\)", "](#connectors)", body)
    # ${CLAUDE_PLUGIN_ROOT} is expanded by Claude Code at load time; in a pasted
    # bundle it has to name a real path inside this pack instead.
    body = body.replace("${CLAUDE_PLUGIN_ROOT}", f"plugins/{plugin}")
    # Absolute Windows/POSIX paths baked in at extraction time are machine-specific.
    body = re.sub(
        r"[A-Za-z]:[\\/][^\s`)\"']*local-agent-mode-sessions[^\s`)\"']*",
        "<this pack's plugin folder>",
        body,
    )
    return body


# --------------------------------------------------------------------------- building

def read_skills(plugin_dir: Path) -> list[tuple[str, dict[str, str], str]]:
    skills = []
    skills_dir = plugin_dir / "skills"
    if not skills_dir.is_dir():
        return skills
    for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
        meta, body = split_frontmatter(skill_md.read_text(encoding="utf-8"))
        name = meta.get("name") or skill_md.parent.name
        skills.append((name, meta, body))
    return skills


def routing_table(plugin: str, skills: list[tuple[str, dict, str]]) -> str:
    rows = ["| Command | Use it when |", "|---|---|"]
    for name, meta, _ in skills:
        desc = meta.get("description", "").replace("|", "\\|")
        if len(desc) > 240:
            desc = desc[:237].rsplit(" ", 1)[0] + "…"
        rows.append(f"| `/{name}` | {desc} |")
    return "\n".join(rows)


def bundle_header(plugin: str, skills: list[tuple[str, dict, str]], connectors: str) -> str:
    title = PLUGIN_TITLES.get(plugin, plugin)
    parts = [
        f"# NNC Skill Pack — {title}",
        "",
        f"<!-- Generated by tools/build_portable.py on {date.today().isoformat()}. Edit plugins/{plugin}/, not this file. -->",
        "",
        "You have the skills below. Treat each one as a procedure you follow **in full** when the",
        "user's request matches it — not as background reading. Rules for all of them:",
        "",
        "1. **Route first.** Match the request to a skill in the table, then follow that skill's",
        "   section verbatim, including its output template.",
        "2. **An explicit command wins.** If the user types the command (`/write-spec`,",
        "   `/status-report`, …), run that skill even if another looks closer.",
        "3. **Ask before inventing.** These skills produce documents people act on. Where a skill",
        "   needs a number, an owner, or a date you do not have, ask — never fill a plausible value.",
        "4. **No tools? Say so once, then proceed.** Skills reference connected systems with `~~`",
        "   placeholders (see Connectors). On a platform without those connections, ask the user to",
        "   paste the data, then run the rest of the skill normally.",
        "5. **Keep the output format.** The templates are the deliverable; don't summarize them away.",
        "",
        "## Routing",
        "",
        routing_table(plugin, skills),
        "",
    ]
    if connectors:
        # Drop CONNECTORS.md's own H1 and nest the rest one level under "## Connectors".
        parts += ["## Connectors", "", demote_headings(connectors, 1).split("\n", 1)[-1].lstrip(), ""]
    return "\n".join(parts)


def build_plugin_bundle(plugin: str) -> str | None:
    plugin_dir = PLUGINS / plugin
    if not plugin_dir.is_dir():
        print(f"  ! skipped {plugin} (not found)", file=sys.stderr)
        return None
    skills = read_skills(plugin_dir)
    if not skills:
        print(f"  ! skipped {plugin} (no skills)", file=sys.stderr)
        return None

    connectors_path = plugin_dir / "CONNECTORS.md"
    connectors = connectors_path.read_text(encoding="utf-8") if connectors_path.exists() else ""

    chunks = [bundle_header(plugin, skills, connectors)]
    for name, meta, body in skills:
        body = rewrite_links(body, plugin)
        body = demote_headings(body, 2)
        # Drop the skill's own H1 if it just repeats the command name.
        body = re.sub(r"^###\s*/?" + re.escape(name) + r"\s*\n+", "", body, count=1)
        chunks.append(
            "\n".join(
                [
                    "---",
                    "",
                    f"## Skill: `/{name}`",
                    "",
                    f"**When to use.** {meta.get('description', '').strip()}",
                    "",
                    (f"**Arguments.** `{meta['argument-hint']}`\n" if meta.get("argument-hint") else ""),
                    body.rstrip(),
                    "",
                ]
            )
        )
    return "\n".join(chunks).replace("\n\n\n\n", "\n\n")


def build_router(bundles: dict[str, list[tuple[str, dict, str]]]) -> str:
    parts = [
        "# NNC Skill Pack — router only",
        "",
        "For platforms with a tight instruction budget. This file lists every skill and what it",
        "does, but not the procedures. Paste it as the standing instruction, then paste the one",
        "relevant `*.bundle.md` section into the chat when you actually run a skill.",
        "",
    ]
    for plugin in PLUGIN_ORDER:
        if plugin not in bundles:
            continue
        parts += [f"## {PLUGIN_TITLES.get(plugin, plugin)}", "", routing_table(plugin, bundles[plugin]), ""]
    return "\n".join(parts)


def main() -> int:
    PORTABLE.mkdir(exist_ok=True)
    all_chunks, collected = [], {}

    print("Building portable bundles…")
    for plugin in PLUGIN_ORDER:
        text = build_plugin_bundle(plugin)
        if text is None:
            continue
        collected[plugin] = read_skills(PLUGINS / plugin)
        out = PORTABLE / f"{plugin}.bundle.md"
        out.write_text(text + "\n", encoding="utf-8")
        kb = len(text.encode("utf-8")) / 1024
        print(f"  + {out.relative_to(ROOT)}  ({len(collected[plugin])} skills, {kb:.0f} KB)")
        all_chunks.append(text)

    combined = "\n".join(
        [
            "# NNC Skill Pack — all in one",
            "",
            f"<!-- Generated by tools/build_portable.py on {date.today().isoformat()}. -->",
            "",
            "Four skill sets in one file. Route to the right one by matching the request against the",
            "routing table at the top of each section; an explicit `/command` always wins.",
            "",
        ]
        + all_chunks
    )
    (PORTABLE / "NNC-ALL-IN-ONE.bundle.md").write_text(combined + "\n", encoding="utf-8")
    print(f"  + portable/NNC-ALL-IN-ONE.bundle.md  ({len(combined.encode('utf-8')) / 1024:.0f} KB)")

    router = build_router(collected)
    (PORTABLE / "ROUTER-ONLY.md").write_text(router + "\n", encoding="utf-8")
    print(f"  + portable/ROUTER-ONLY.md  ({len(router.encode('utf-8')) / 1024:.0f} KB)")

    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
